name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Build
        run: |
          npm install -g @angular/cli
          npm install
          ng build --prod
      - uses: actions/checkout@v2
      - name: Angular Deploy gh-pages Actions
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          github_access_token: ${{ secrets.JS_QUIZ }}
          build_configuration:
          base_href: /js-quiz/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/js-quiz
          angular_project_dir:
